#!/usr/bin/env bash
# Produce the verification transcript from a clean clone of HEAD.
#
# Committed rather than run ad hoc so the evidence is reproducible: anyone can
# re-run this and get the same twelve sections, and a reviewer can read exactly
# what was executed instead of trusting a summary. Earlier transcripts were
# assembled by hand from several shells and several commits, and an independent
# review rejected them twice for precisely that.
#
# Usage:  scripts/verify.sh [output-file]
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$REPO/docs/operations/verification-transcript.txt}"
CLONE_PARENT="$(mktemp -d)"
CLONE="$CLONE_PARENT/capmap-verify"
SHA="$(git -C "$REPO" rev-parse HEAD)"
SHORT="$(git -C "$REPO" rev-parse --short HEAD)"

# Setup is checked, not assumed. A failed clone, checkout or cd used to leave the
# script running in the wrong directory, and an output path that cannot be opened
# skipped the whole redirected block below while still exiting 0 — a verification
# runner that produces no transcript and reports success.
die() { echo "$1" >&2; exit 1; }

# Everything this run creates under the system temporary directory, removed when
# it finishes cleanly. A clone with its node_modules is ~100 MB and three of
# these are made per run; a session of repeated runs left 3.4 GB behind. On
# failure they are kept and their paths printed, because that is when you want
# to look inside them.
SCRATCH_DIRS=()
cleanup() {
  if [ "$FAILED" -eq 0 ]; then
    rm -rf "${SCRATCH_DIRS[@]}" 2>/dev/null
  else
    echo "kept for inspection: ${SCRATCH_DIRS[*]}" >&2
  fi
}

: > "$OUT" || die "cannot write the transcript to $OUT"
git clone -q "$REPO" "$CLONE" || die "could not clone $REPO into $CLONE"
git -C "$CLONE" checkout -q "$SHA" || die "could not check out $SHA in the clone"
cd "$CLONE" || die "could not enter the clone at $CLONE"

# Exported once, from the clone and from the index the clone carries, so no
# section depends on what the caller happened to have in its shell. The estate
# root is read from the index's own manifest: the index is the artifact under
# test and it records the tree it was built from.
export CAPMAP_CONFIG_DIR="$CLONE/config"
export CAPMAP_ROOT="$(node -p "require('$CLONE/index/index.json').root")"

# Each step prints the command, its full output and its exit code — AND records
# the failure. Printing "exit 1" into a transcript while the script itself
# returns 0 produces a document that looks like evidence of success and a runner
# that cannot be used as a gate; an independent review found exactly that here.
FAILED=0
FAILED_STEPS=""
SCRATCH_DIRS+=("$CLONE_PARENT")
step() {
  local label="$1"; shift
  echo "\$ $label"
  local o rc
  o="$("$@" 2>&1)"; rc=$?
  echo "$o"
  echo "exit $rc"
  echo
  if [ "$rc" -ne 0 ]; then FAILED=$((FAILED + 1)); FAILED_STEPS="$FAILED_STEPS
    $label (exit $rc)"; fi
}

# For sections that are a pipeline rather than a single command.
record() {
  local label="$1" rc="$2"
  if [ "$rc" -ne 0 ]; then FAILED=$((FAILED + 1)); FAILED_STEPS="$FAILED_STEPS
    $label (exit $rc)"; fi
}

# For conditions that were being printed rather than checked. `ls` on four entry
# points shows whether they are there to a reader and to nothing else; the same
# defect was found in the Linux runner's identity probes and it is the same
# defect here.
assert() {
  local label="$1"; shift
  if "$@" >/dev/null 2>&1; then
    echo "  ok   $label"
  else
    echo "  FAIL $label"
    record "$label" 1
  fi
}

{
echo "==================================================================="
echo " CAPMAP VERIFICATION TRANSCRIPT"
echo " Generated by scripts/verify.sh — re-runnable, not hand-assembled."
echo "==================================================================="
echo
echo "PROVENANCE"
echo "  Code commit under test: $SHA"
echo "  Code tree digest: $(node scripts/code-digest.mjs "$SHA")"
echo "  (the digest outlives a squash or rebase merge; the provenance check"
echo "  falls back to it when the commit is no longer in the history)"
echo "  TWO clean clones of that ONE commit are used:"
echo "    A) $(uname -srm), node $(node --version) — sections 1-9"
echo "    B) Linux, docker node:22-bookworm-slim — section 10"
echo "  Both print the same commit and the same index generatedAt, so both ran"
echo "  against identical code and identical data. The index is a tracked"
echo "  artifact of the commit and is NOT regenerated during verification."
echo "  A transcript is a tracked file, so it can never name the commit that"
echo "  contains it: committing it moves HEAD. The claim that matters is that"
echo "  nothing since $SHORT touches code, and it is checked rather than asserted:"
echo "    node scripts/check-transcript-provenance.mjs"
echo "  date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
# The clone's own status is 0 by construction and says nothing. What a reader
# needs is whether the tree this was generated FROM carried anything the commit
# under test does not — this transcript being rewritten in place is expected.
DIRTY="$(git -C "$REPO" status --porcelain)"
echo "  Uncommitted in the source tree at generation time:"
if [ -z "$DIRTY" ]; then echo "    none"; else echo "$DIRTY" | sed 's/^/    /'; fi
echo

# Sourced, not executed, so the sections share this shell's helpers, counters and
# redirection. `|| die` matters: a missing section file would otherwise leave the
# transcript quietly short of half its sections while everything else reported
# success — which is the defect this whole runner has been rebuilt around.
LIB="$CLONE/scripts/lib"
# shellcheck source=lib/verify-build.sh
. "$LIB/verify-build.sh" || die "could not run the build and index sections from $LIB"
# shellcheck source=lib/verify-gates.sh
. "$LIB/verify-gates.sh" || die "could not run the gate sections from $LIB"

echo "=== RESULT OF THIS RUN ==="
if [ "$FAILED" -eq 0 ]; then
  echo "  every check above met its expectation"
  echo "  note: section 8a EXPECTS exit 1 — an index claiming an export the"
  echo "  source does not have must be rejected, so exit 0 there is the failure"
else
  echo "  $FAILED check(s) did NOT meet their expectation:$FAILED_STEPS"
fi
echo
} > "$OUT" 2>&1

echo "wrote $OUT"
echo "section 10 (Linux) is appended by scripts/verify-linux.sh, which needs"
echo "a container; sections 11-14 by scripts/verify-live.sh, which needs a"
echo "model credential."
if [ "$FAILED" -ne 0 ]; then
  echo "$FAILED step(s) failed — see '=== RESULT OF THIS RUN ===' in $OUT" >&2
fi
cleanup
exit $([ "$FAILED" -eq 0 ] && echo 0 || echo 1)
